google_auth:
  client_id: ""
  client_secret: ""
captcha:
  site_key: ""
  secret_key: ""
basic_auth:
  username: "admin"
  password: ""
api_admin_token: "TOKEN"
app_token: "TOKEN"
aws_s3:
  access_key_id: ""
  secret_access_key: ""
rails_db_pasworkd: ""
rollbar_token: ""
sendgrid_api_key: ""
